"""Add volume_cm3 to product

Revision ID: 270832e39f09
Revises: 40ea77881dee
Create Date: 2026-08-09 18:07:46.915516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '270832e39f09'
down_revision: Union[str, Sequence[str], None] = '40ea77881dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('volume_cm3', sa.Numeric(precision=10, scale=2), server_default='100.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'volume_cm3')
    # ### end Alembic commands ###
