"""Add MacroOrder model

Revision ID: 40ea77881dee
Revises: 68f8a3bfafdc
Create Date: 2026-08-08 21:28:43.589081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '40ea77881dee'
down_revision: Union[str, Sequence[str], None] = '68f8a3bfafdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference_number', sa.String(length=50), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'IN_WAVE', 'PICKED_BATCH', 'SORTED', 'PACKED', 'SHIPPED', 'CANCELLED', name='orderstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_orders_reference_number'), 'macro_orders', ['reference_number'], unique=True)
    op.add_column('orders', sa.Column('macro_order_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'macro_orders', ['macro_order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'macro_order_id')
    op.drop_index(op.f('ix_macro_orders_reference_number'), table_name='macro_orders')
    op.drop_table('macro_orders')
    # ### end Alembic commands ###
