"""Add efficiency to User and wave_orders to Order

Revision ID: 68f8a3bfafdc
Revises: a15babe6d3ee
Create Date: 2026-08-08 20:34:32.504784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f8a3bfafdc'
down_revision: Union[str, Sequence[str], None] = 'a15babe6d3ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('efficiency', sa.Float(), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'efficiency')
    # ### end Alembic commands ###
