"""add_shift_events

Revision ID: bb58ae9ed22c
Revises: c92becbd3516
Create Date: 2026-08-09 19:50:13.569607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb58ae9ed22c'
down_revision: Union[str, Sequence[str], None] = 'c92becbd3516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('LOGIN', 'LOGOUT', 'BREAK_START', 'BREAK_END', 'IDLE_START', 'IDLE_END', name='shifteventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('shifts', sa.Column('total_volume_cm3', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('shifts', sa.Column('total_orders_completed', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'total_orders_completed')
    op.drop_column('shifts', 'total_volume_cm3')
    op.drop_table('shift_events')
    # ### end Alembic commands ###
