"""add_cart_capacity_to_user

Revision ID: c92becbd3516
Revises: 270832e39f09
Create Date: 2026-08-09 19:09:34.855795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92becbd3516'
down_revision: Union[str, Sequence[str], None] = '270832e39f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cart_capacity_items', sa.Integer(), server_default='15', nullable=False))
    op.add_column('users', sa.Column('current_cart_items', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_cart_items')
    op.drop_column('users', 'cart_capacity_items')
    # ### end Alembic commands ###
